//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package application;

import org.androidannotations.api.BackgroundExecutor;

public final class App_
        extends App {

    private static App INSTANCE_;

    public static App getInstance() {
        return INSTANCE_;
    }

    /**
     * Visible for testing purposes
     * 
     */
    public static void setForTesting(App application) {
        INSTANCE_ = application;
    }

    @Override
    public void onCreate() {
        INSTANCE_ = this;
        init_();
        super.onCreate();
    }

    private void init_() {
    }

    @Override
    public void initGetAccountDetail() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("update_user_info", 0, "") {


                                       @Override
                                       public void execute() {
                                           try {
                                               App_.super.initGetAccountDetail();
                                           } catch (Throwable e) {
                                               Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                                           }
                                       }

                                   }
        );
    }

    @Override
    public void setUpdateReceiver() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


                                       @Override
                                       public void execute() {
                                           try {
                                               App_.super.setUpdateReceiver();
                                           } catch (Throwable e) {
                                               Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                                           }
                                       }

                                   }
        );
    }

}
