//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package activity;

import android.content.Context;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.view.inputmethod.InputMethodManager;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.ListView;
import com.parse.ParseObject;
import com.softcsoftware.aio.R.id;
import com.softcsoftware.aio.R.layout;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;
import views.Sliding.SlidingView;

public final class AHome_
        extends AHome
        implements HasViews, OnViewChangedListener {

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    public static AHome_.IntentBuilder_ intent(Context context) {
        return new AHome_.IntentBuilder_(context);
    }

    public static AHome_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new AHome_.IntentBuilder_(fragment);
    }

    public static AHome_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new AHome_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.home_activity);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        input_method_manager = ((InputMethodManager) this.getSystemService(Context.INPUT_METHOD_SERVICE));
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt() < 5) && (keyCode == KeyEvent.KEYCODE_BACK)) && (event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        searchInput = ((EditText) hasViews.findViewById(id.edit_search));
        slidingView = ((SlidingView) hasViews.findViewById(id.sliding_layout));
        searchButton = ((ImageButton) hasViews.findViewById(id.bnt_search));
        listView = ((ListView) hasViews.findViewById(id.list_view));
        {
            View view = hasViews.findViewById(id.about_us);
            if (view != null) {
                view.setOnClickListener(new OnClickListener() {


                                            @Override
                                            public void onClick(View view) {
                                                AHome_.this.open_about_us();
                                            }

                                        }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.legal_info);
            if (view != null) {
                view.setOnClickListener(new OnClickListener() {


                                            @Override
                                            public void onClick(View view) {
                                                AHome_.this.open_legal_info();
                                            }

                                        }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.video_websites);
            if (view != null) {
                view.setOnClickListener(new OnClickListener() {


                                            @Override
                                            public void onClick(View view) {
                                                AHome_.this.update_video_adapter();
                                            }

                                        }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.hot_websites);
            if (view != null) {
                view.setOnClickListener(new OnClickListener() {


                                            @Override
                                            public void onClick(View view) {
                                                AHome_.this.update_hot_adapter();
                                            }

                                        }
                );
            }
        }
        if (searchButton != null) {
            searchButton.setOnClickListener(new OnClickListener() {


                                                @Override
                                                public void onClick(View view) {
                                                    AHome_.this.search_popup();
                                                }

                                            }
            );
        }
        {
            View view = hasViews.findViewById(id.music_websites);
            if (view != null) {
                view.setOnClickListener(new OnClickListener() {


                                            @Override
                                            public void onClick(View view) {
                                                AHome_.this.update_music_adapter();
                                            }

                                        }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.update);
            if (view != null) {
                view.setOnClickListener(new OnClickListener() {


                                            @Override
                                            public void onClick(View view) {
                                                AHome_.this.check_new_update();
                                            }

                                        }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.open_help);
            if (view != null) {
                view.setOnClickListener(new OnClickListener() {


                                            @Override
                                            public void onClick(View view) {
                                                AHome_.this.open_help_page();
                                            }

                                        }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.add_new_download_button);
            if (view != null) {
                view.setOnClickListener(new OnClickListener() {


                                            @Override
                                            public void onClick(View view) {
                                                AHome_.this.show_add_new_dialog();
                                            }

                                        }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.download_manager);
            if (view != null) {
                view.setOnClickListener(new OnClickListener() {


                                            @Override
                                            public void onClick(View view) {
                                                AHome_.this.open_download_manager();
                                            }

                                        }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.privacy_policy);
            if (view != null) {
                view.setOnClickListener(new OnClickListener() {


                                            @Override
                                            public void onClick(View view) {
                                                AHome_.this.open_privacy_policy();
                                            }

                                        }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.youtube_video_downloader);
            if (view != null) {
                view.setOnClickListener(new OnClickListener() {


                                            @Override
                                            public void onClick(View view) {
                                                AHome_.this.open_youtube_site();
                                            }

                                        }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.share);
            if (view != null) {
                view.setOnClickListener(new OnClickListener() {


                                            @Override
                                            public void onClick(View view) {
                                                AHome_.this.share_with_friend();
                                            }

                                        }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.facebook_like);
            if (view != null) {
                view.setOnClickListener(new OnClickListener() {


                                            @Override
                                            public void onClick(View view) {
                                                AHome_.this.open_facebook_app();
                                            }

                                        }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.setting);
            if (view != null) {
                view.setOnClickListener(new OnClickListener() {


                                            @Override
                                            public void onClick(View view) {
                                                AHome_.this.ope_app_settings();
                                            }

                                        }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.open_website);
            if (view != null) {
                view.setOnClickListener(new OnClickListener() {


                                            @Override
                                            public void onClick(View view) {
                                                AHome_.this.open_project_website();
                                            }

                                        }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.twitter_follow);
            if (view != null) {
                view.setOnClickListener(new OnClickListener() {


                                            @Override
                                            public void onClick(View view) {
                                                AHome_.this.open_twitter_app();
                                            }

                                        }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.option_button);
            if (view != null) {
                view.setOnClickListener(new OnClickListener() {


                                            @Override
                                            public void onClick(View view) {
                                                AHome_.this.navigation_option_button_press();
                                            }

                                        }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.report_bug);
            if (view != null) {
                view.setOnClickListener(new OnClickListener() {


                                            @Override
                                            public void onClick(View view) {
                                                AHome_.this.report_bug();
                                            }

                                        }
                );
            }
        }
        onCreateFinish();
        open_website();
    }

    @Override
    public void show_message_from_parse(final ParseObject parseObject, final String name, final String message) {
        handler_.post(new Runnable() {


                          @Override
                          public void run() {
                              AHome_.super.show_message_from_parse(parseObject, name, message);
                          }

                      }
        );
    }

    @Override
    public void init_check_message_from_parse() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("check_message_from_parse", 0, "") {


                                       @Override
                                       public void execute() {
                                           try {
                                               AHome_.super.init_check_message_from_parse();
                                           } catch (Throwable e) {
                                               Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                                           }
                                       }

                                   }
        );
    }

    public static class IntentBuilder_
            extends ActivityIntentBuilder<AHome_.IntentBuilder_> {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, AHome_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), AHome_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), AHome_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_ != null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_ != null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
